import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import PersonTable from "./components/table";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>LOL Esports Manager</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          LOL Esports Manager
          <a href="https://lole.qq.com/main.html"> Analysis!</a>
        </h1>

        <div className={styles.grid}>
          <PersonTable />
        </div>
      </main>
    </div>
  );
};

export default Home;
